# Self-Attention cacultate practice with numpy
Ref:
[Step-by-step guide to self-attention with illustrations and code](https://towardsdatascience.com/illustrated-self-attention-2d627e33b20a#570c)

In [1]:
import numpy as np
from scipy.special import softmax

## Input

In [2]:
input_1 = np.array([1, 0, 1, 0], dtype='float32')
input_2 = np.array([0, 2, 0, 2], dtype='float32')
input_3 = np.array([1, 1, 1, 1], dtype='float32')

## Weight

In [3]:
wk = np.array([[0, 0, 1],
             [1, 1, 0],
             [0, 1, 0],
             [1, 1, 0]], dtype='float32')
wq = np.array([[1, 0, 1],
             [1, 0, 0],
             [0, 0, 1],
             [0, 1, 1]], dtype='float32')
wv = np.array([[0, 2, 0],
             [0, 3, 0],
             [1, 0, 3],
             [1, 1, 0]], dtype='float32')

## Calculate Key Representations

### Calculate for input

In [4]:
print(input_1.dot(wk))
print(input_2.dot(wk))
print(input_3.dot(wk))

[0. 1. 1.]
[4. 4. 0.]
[2. 3. 1.]


### Calculate for inputs

In [5]:
inputs = np.vstack([input_1,input_2,input_3])
print(inputs)

[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


In [6]:
inputs.dot(wk) # same with "compute KR"

array([[0., 1., 1.],
       [4., 4., 0.],
       [2., 3., 1.]], dtype=float32)

## Calculate QKV representations

In [7]:
query_representations = inputs.dot(wq)
key_representations = inputs.dot(wk)
value_representations = inputs.dot(wv)

In [8]:
print(query_representations,"\n")
print(key_representations,"\n")
print(value_representations,"\n")

[[1. 0. 2.]
 [2. 2. 2.]
 [2. 1. 3.]] 

[[0. 1. 1.]
 [4. 4. 0.]
 [2. 3. 1.]] 

[[1. 2. 3.]
 [2. 8. 0.]
 [2. 6. 3.]] 



## Calculate attention scores for Inputs

### Attention scores =  softmax(query_representations * key_representations) * value_representations

![](https://picb.zhimg.com/80/v2-752c1c91e1b4dbca1b64f59a7e026b9b_720w.jpg)

In [9]:
attention_scores = query_representations.dot(np.transpose(key_representations))
print(attention_scores)

[[ 2.  4.  4.]
 [ 4. 16. 12.]
 [ 4. 12. 10.]]


### Calculate softmax

In [10]:
_softmax_attn_score = softmax(attention_scores[0])
print(_softmax_attn_score)

[0.06337894 0.46831056 0.46831056]


### Weighted values

In [11]:
for attention_score in attention_scores:
    weighted_values = np.multiply(value_representations,np.transpose([softmax(attention_score)]))
    print(np.sum(weighted_values,axis=0))

[1.9366212 6.6831055 1.5950685]
[1.9999939 7.963991  0.0539764]
[1.9997054  7.7598953  0.35838947]
